# Generated by Django 5.0.6 on 2024-06-24 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=100, verbose_name='FullName')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
                ('City', models.CharField(max_length=100, verbose_name='City')),
                ('ApartmentSize', models.CharField(max_length=100, verbose_name='ApartmentSize')),
                ('message', models.CharField(max_length=100, verbose_name='message')),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='UserData.user')),
            ],
        ),
    ]
