# Generated by Django 5.0.6 on 2024-06-24 12:03

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mainproperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='./images/')),
                ('image1', models.ImageField(upload_to='./images/')),
                ('image2', models.ImageField(upload_to='./images/')),
                ('title', models.CharField(max_length=100, verbose_name='Post Title')),
                ('details', models.CharField(max_length=1000, verbose_name='Post Details')),
                ('PostDate', models.DateField(default=datetime.date.today)),
                ('WriterName', models.CharField(max_length=100, verbose_name='Write Name')),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='UserData.user')),
            ],
        ),
    ]
