# Generated by Django 5.0.6 on 2024-07-03 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainpropertyData', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainproperty',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='mainproperty',
            name='image2',
        ),
        migrations.AlterField(
            model_name='mainproperty',
            name='image',
            field=models.CharField(max_length=100),
        ),
    ]
