# Generated by Django 5.0.6 on 2024-07-03 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainpropertyData', '0002_remove_mainproperty_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainproperty',
            name='image',
            field=models.ImageField(upload_to='img/media/images/'),
        ),
    ]
