# Generated by Django 5.0.6 on 2024-06-24 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=100, verbose_name='First name')),
                ('Lastname', models.CharField(max_length=100, verbose_name='last name')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
                ('subject', models.CharField(max_length=100, verbose_name='subject')),
                ('message', models.CharField(max_length=100, verbose_name='message')),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='UserData.user')),
            ],
        ),
    ]
